site_name: SpaceEx-tutorials
site_url: "https://nikos-kekatos.github.io/SpaceEx-tutorials"

theme: 'material'

pages:
    - Introduction: index.md
    - Running SpaceEx from the terminal: readme_terminal.md
    - Example: example.md
    - Plotting: plotting.md
    - Running mutliple configurations: multiple.md
